-- 구성원 (교수 프로필은 이 테이블이 아니라 앱 localStorage에 있다)
create table if not exists public.members (
  id bigint generated by default as identity primary key,
  member_group text not null check (
    member_group in ('postdocs', 'gradStudents', 'phdAlumni', 'msAlumni')
  ),
  name_ko text not null,
  name_en text not null,
  degree text not null,
  email text,
  research text,
  graduation_date date,
  photo_url text,
  created_at timestamptz not null default now()
);

create index if not exists members_group_idx on public.members (member_group);

alter table public.members enable row level security;

drop policy if exists "members_public_read" on public.members;
drop policy if exists "members_authenticated_write" on public.members;
create policy "members_public_read" on public.members for select using (true);
-- 쓰기 권한은 로그인 여부가 아니라 public.admin_users 등록 여부로 결정된다
-- (admins.sql 참고).
drop policy if exists "members_admin_write" on public.members;
create policy "members_admin_write" on public.members for all to authenticated using (public.is_admin()) with check (public.is_admin());
