-- 뉴스 사진 (news 테이블 선행 필요)
create table if not exists public.news_photos (
  id bigint generated by default as identity primary key,
  news_id bigint not null references public.news(id) on delete cascade,
  url text not null,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists news_photos_news_id_idx on public.news_photos (news_id);

alter table public.news_photos enable row level security;

drop policy if exists "news_photos_public_read" on public.news_photos;
drop policy if exists "news_photos_authenticated_write" on public.news_photos;
create policy "news_photos_public_read" on public.news_photos for select using (true);
-- 쓰기 권한은 로그인 여부가 아니라 public.admin_users 등록 여부로 결정된다
-- (admins.sql 참고).
drop policy if exists "news_photos_admin_write" on public.news_photos;
create policy "news_photos_admin_write" on public.news_photos for all to authenticated using (public.is_admin()) with check (public.is_admin());
