-- 뉴스
create table if not exists public.news (
  id bigint generated by default as identity primary key,
  type text not null,
  date text not null,
  title text not null,
  detail text not null,
  author text not null default '',
  view_count bigint not null default 0,
  pinned boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists news_pinned_idx on public.news (pinned) where pinned = true;

alter table public.news enable row level security;

drop policy if exists "news_public_read" on public.news;
drop policy if exists "news_authenticated_write" on public.news;
create policy "news_public_read" on public.news for select using (true);
-- 쓰기 권한은 로그인 여부가 아니라 public.admin_users 등록 여부로 결정된다
-- (admins.sql 참고).
drop policy if exists "news_admin_write" on public.news;
create policy "news_admin_write" on public.news for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- RPC: 상세 페이지에서 view_count 증가 (비로그인 호출 안전)
create or replace function public.increment_news_view_count(p_news_id bigint)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_count bigint;
begin
  update public.news
  set view_count = view_count + 1
  where id = p_news_id
  returning view_count into new_count;

  return new_count;
end;
$$;

grant execute on function public.increment_news_view_count(bigint) to anon, authenticated;
