-- 뉴스 첨부파일 (news 테이블 선행 필요)
create table if not exists public.news_file (
  id bigint generated by default as identity primary key,
  news_id bigint not null references public.news(id) on delete cascade,
  url text not null,
  file_name text not null,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists news_file_news_id_idx on public.news_file (news_id);

alter table public.news_file enable row level security;

drop policy if exists "news_file_public_read" on public.news_file;
drop policy if exists "news_file_authenticated_write" on public.news_file;
create policy "news_file_public_read" on public.news_file for select using (true);
-- 쓰기 권한은 로그인 여부가 아니라 public.admin_users 등록 여부로 결정된다
-- (admins.sql 참고).
drop policy if exists "news_file_admin_write" on public.news_file;
create policy "news_file_admin_write" on public.news_file for all to authenticated using (public.is_admin()) with check (public.is_admin());
