-- 특허 (date는 text로 저장, YYYY-MM-DD 권장)
create table if not exists public.patents (
  id bigint generated by default as identity primary key,
  number text not null,
  title text not null,
  title_en text not null,
  date text not null,
  status text not null check (status in ('registered', 'pending')),
  inventors text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.patents enable row level security;

drop policy if exists "patents_public_read" on public.patents;
drop policy if exists "patents_authenticated_write" on public.patents;
create policy "patents_public_read" on public.patents for select using (true);
-- 쓰기 권한은 로그인 여부가 아니라 public.admin_users 등록 여부로 결정된다
-- (admins.sql 참고).
drop policy if exists "patents_admin_write" on public.patents;
create policy "patents_admin_write" on public.patents for all to authenticated using (public.is_admin()) with check (public.is_admin());
