-- 논문
create table if not exists public.publications (
  id bigint generated by default as identity primary key,
  title_ko text not null,
  title_en text not null,
  authors text not null,
  journal text not null,
  doi text not null default '',
  doi_link text,
  published_at date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists publications_published_at_idx on public.publications (published_at desc);

alter table public.publications enable row level security;

drop policy if exists "publications_public_read" on public.publications;
drop policy if exists "publications_authenticated_write" on public.publications;
create policy "publications_public_read" on public.publications for select using (true);
-- 쓰기 권한은 로그인 여부가 아니라 public.admin_users 등록 여부로 결정된다
-- (admins.sql 참고).
drop policy if exists "publications_admin_write" on public.publications;
create policy "publications_admin_write" on public.publications for all to authenticated using (public.is_admin()) with check (public.is_admin());
