-- Normalized schema (user-defined columns) — id is bigint auto-increment

drop table if exists public.members cascade;
drop table if exists public.patents cascade;
drop table if exists public.gallery cascade;
drop table if exists public.publications cascade;
drop table if exists public.news cascade;

create table public.news (
  id bigint generated by default as identity primary key,
  type text not null,
  date text not null,
  title text not null,
  detail text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.publications (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('Journal', 'Conference')),
  title_ko text not null,
  title_en text not null,
  authors text not null,
  journal text not null,
  doi text not null default '',
  doi_link text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.gallery (
  id bigint generated by default as identity primary key,
  title text not null,
  date text not null,
  type text not null check (type in ('Member', 'Conference', '기타')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.patents (
  id bigint generated by default as identity primary key,
  number text not null,
  title text not null,
  title_en text not null,
  date text not null,
  status text not null check (status in ('registered', 'pending')),
  inventors text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.members (
  id bigint generated by default as identity primary key,
  member_group text not null check (
    member_group in ('postdocs', 'gradStudents', 'phdAlumni', 'msAlumni')
  ),
  name_ko text not null,
  name_en text not null,
  degree text not null,
  email text,
  field_kr text,
  field_en text,
  graduation_date date,
  created_at timestamptz not null default now()
);

create index members_group_idx on public.members (member_group);

alter table public.news enable row level security;
alter table public.publications enable row level security;
alter table public.gallery enable row level security;
alter table public.patents enable row level security;
alter table public.members enable row level security;

drop policy if exists "news_public_read" on public.news;
create policy "news_public_read" on public.news for select using (true);
drop policy if exists "publications_public_read" on public.publications;
create policy "publications_public_read" on public.publications for select using (true);
drop policy if exists "gallery_public_read" on public.gallery;
create policy "gallery_public_read" on public.gallery for select using (true);
drop policy if exists "patents_public_read" on public.patents;
create policy "patents_public_read" on public.patents for select using (true);
drop policy if exists "members_public_read" on public.members;
create policy "members_public_read" on public.members for select using (true);

drop policy if exists "news_authenticated_write" on public.news;
create policy "news_authenticated_write" on public.news for all to authenticated using (true) with check (true);
drop policy if exists "publications_authenticated_write" on public.publications;
create policy "publications_authenticated_write" on public.publications for all to authenticated using (true) with check (true);
drop policy if exists "gallery_authenticated_write" on public.gallery;
create policy "gallery_authenticated_write" on public.gallery for all to authenticated using (true) with check (true);
drop policy if exists "patents_authenticated_write" on public.patents;
create policy "patents_authenticated_write" on public.patents for all to authenticated using (true) with check (true);
drop policy if exists "members_authenticated_write" on public.members;
create policy "members_authenticated_write" on public.members for all to authenticated using (true) with check (true);
